{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "fcfca6a4-a045-41b7-b44f-633677dece57",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import PyPDF2 as pdf\n",
    "import streamlit as st\n",
    "from dotenv import load_dotenv\n",
    "import google.generativeai as genai\n",
    "\n",
    "# Load the environment variables\n",
    "load_dotenv()\n",
    "genai.configure(api_key=os.getenv(\"AIzaSyCgFVkWrlgMjxJdzMxtaUp9EG67p8H-UQo\"))\n",
    "model = genai.GenerativeModel('gemini-pro')\n",
    "\n",
    "# Set page config\n",
    "st.set_page_config(page_title=\"Resume Cabin\", page_icon=\":robot:\", layout=\"wide\")\n",
    "\n",
    "# Background image and style\n",
    "page_bg_img = \"\"\"\n",
    "<style>\n",
    "[data-testid=\"stAppViewContainer\"] > .main {\n",
    "background-color: #002b2f;\n",
    "background-image: url(\"https://images.unsplash.com/photo-1588420343618-6141b3784bce?q=80&w=2012&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D\");\n",
    "background-size: cover;\n",
    "background-position: center;\n",
    "background-repeat: no-repeat;\n",
    "background-attachment: fixed;\n",
    "}\n",
    "\n",
    "[data-testid=\"stHeader\"] {\n",
    "background: rgba(0,0,0,0);\n",
    "}\n",
    "\n",
    "[data-testid=\"stToolbar\"] {\n",
    "visibility: hidden;\n",
    "}\n",
    "\n",
    "h1 {\n",
    "color: #ffffff;\n",
    "text-align: center;\n",
    "font-family: Arial, Helvetica, sans-serif;\n",
    "font-size: 3em;\n",
    "}\n",
    "\n",
    "h2, h3, h4 {\n",
    "color: #ffffff;\n",
    "font-family: Arial, Helvetica, sans-serif;\n",
    "}\n",
    "\n",
    "p, label {\n",
    "color: #dcdcdc;\n",
    "font-family: Arial, Helvetica, sans-serif;\n",
    "}\n",
    "\n",
    "button {\n",
    "background-color: #28a745;\n",
    "color: #ffffff;\n",
    "border-radius: 5px;\n",
    "padding: 10px 20px;\n",
    "font-size: 1.2em;\n",
    "border: none;\n",
    "}\n",
    "\n",
    "button:hover {\n",
    "background-color: #218838;\n",
    "}\n",
    "\n",
    "textarea, .stFileUploader {\n",
    "background-color: white;\n",
    "color: black;\n",
    "border: 1px solid #555555;\n",
    "}\n",
    "\n",
    ".st-bd {\n",
    "background-color: #28a745;\n",
    "}\n",
    "</style>\n",
    "\"\"\"\n",
    "\n",
    "st.markdown(page_bg_img, unsafe_allow_html=True)\n",
    "\n",
    "# Title and description\n",
    "st.title(\"Resume Check: Instantly Check Your Resume for 30+ Issues\")\n",
    "st.write(\"Improve Your Resume ATS Score\")\n",
    "\n",
    "# Job Description input\n",
    "st.subheader(\"Paste the Job Description\")\n",
    "jd = st.text_area(\"\", height=150)\n",
    "\n",
    "# Resume upload\n",
    "st.subheader(\"Upload Your Resume\")\n",
    "uploaded_file = st.file_uploader(\"\", type=\"pdf\", help=\"Please upload the PDF\")\n",
    "\n",
    "# Submit button\n",
    "submit = st.button(\"Check ATS Score\")\n",
    "\n",
    "# Processing the input\n",
    "if submit:\n",
    "    if uploaded_file is not None:\n",
    "        reader = pdf.PdfReader(uploaded_file)\n",
    "        extracted_text = \"\"\n",
    "        for page in range(len(reader.pages)):\n",
    "            page = reader.pages[page]\n",
    "            extracted_text += page.extract_text()\n",
    "        \n",
    "        # Generating response using the model\n",
    "        input_prompt = f\"\"\"\n",
    "        You are an advanced and highly experienced Applicant Tracking System (ATS) with specialized knowledge in the finance industry, including roles such as quant trader, junior trader, trading analyst, and other finance-related positions. Your primary task is to evaluate resumes based on the provided job description. Considering the highly competitive job market, your goal is to offer the best possible guidance for enhancing resumes.\n",
    "\n",
    "        Responsibilities:\n",
    "        1. Assess resumes with a high degree of accuracy against the job description.\n",
    "        2. Identify and highlight missing keywords crucial for the role.\n",
    "        3. Provide a percentage match score reflecting the resume's alignment with the job requirements on the scale of 1-100.\n",
    "        4. Offer detailed feedback for improvement to help candidates stand out.\n",
    "        5. Analyze the Resume, Job description and industry trends and provide personalized suggestions for skills, keywords, and achievements that can enhance the provided resume.\n",
    "        6. Provide suggestions for improving the language, tone, and clarity of the resume content.\n",
    "        7. Provide users with insights into the performance of their resumes. Track the metrics such as - a) Application Success rates b) Views c) Engagement. Provide valuable feedback to improve the candidate's chances in the job market. Use your trained knowledge of Gemini trained data. Provide an application success rate on the scale of 1-100.\n",
    "\n",
    "        After every time a user refreshes a page, if the provided job description and resume are the same, then always give the same result. \n",
    "\n",
    "        Field-Specific Customizations:\n",
    "\n",
    "        Quant Trader:\n",
    "        You are an advanced and highly experienced Applicant Tracking System (ATS) with specialized knowledge in quantitative trading. Your primary task is to evaluate resumes for quantitative trader roles. This includes analyzing skills in financial modeling, statistical analysis, and algorithmic trading. You should be able to assess candidates' familiarity with market data, risk management, and trading strategies.\n",
    "\n",
    "        Junior Trader:\n",
    "        You are an advanced and highly experienced Applicant Tracking System (ATS) with specialized knowledge in junior trading roles. You should evaluate candidates for their understanding of financial markets, technical analysis, and trading strategies. This includes analyzing their ability to make quick decisions based on market trends and financial data.\n",
    "\n",
    "        Trading Analyst:\n",
    "        You are an advanced and highly experienced Applicant Tracking System (ATS) with specialized knowledge in trading analysis. Your primary task is to evaluate resumes for trading analyst roles. You should be able to assess candidates' proficiency in analyzing market data, understanding trends, and making data-driven decisions in fast-paced environments.\n",
    "\n",
    "        Finance-Related Roles:\n",
    "        You are an advanced and highly experienced Applicant Tracking System (ATS) with specialized knowledge in various finance-related roles. This includes risk management, portfolio management, financial analysis, and more. You should evaluate resumes based on proficiency in financial modeling, data analysis, and an understanding of financial markets and instruments.\n",
    "\n",
    "        Resume: {extracted_text}\n",
    "        Description: {jd}\n",
    "\n",
    "        I want the only response in 4 sectors as follows:\n",
    "        • Job Description Match: \\n\\n\n",
    "        • Missing Keywords: \\n\\n\n",
    "        • Profile Summary: \\n\\n\n",
    "        • Personalized suggestions for skills, keywords, and achievements that can enhance the provided resume: \\n\\n\n",
    "        • Application Success rates: \\n\\n\n",
    "        \"\"\"\n",
    "        \n",
    "        response = model.generate_content(input_prompt)\n",
    "        st.subheader(\"Analysis Result\")\n",
    "        st.write(response.text)\n",
    "    else:\n",
    "        st.error(\"Please upload a resume to continue.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
